#version: '3.8'
services:
  flask-app:
    build: .
    container_name: flask_onnx_app
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_MODEL_KEY=${S3_MODEL_KEY}
    restart: unless-stopped
