name: CI Pipeline with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src/ utils/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Build Docker image
        run: |
          docker build -t mlops-app .
