name: Pruebas Unitarias

on:
  push:
    branches:
      - dev

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Añadir la raíz del proyecto al PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Definir variables de entorno necesarias para pruebas
        run: |
          echo "S3_BUCKET_NAME=modelo-onnx" >> $GITHUB_ENV
          echo "S3_MODEL_KEY=densenet121_Opset17.onnx" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Ejecutar pruebas unitarias con Pytest
        run: pytest
